Xerox/FieryEX550_560_ElCapitan.download.recipe, Xerox/FieryEX550_560_ElCapitan.pkg.recipe, Xerox/FieryEX550_560_Yosemite.pkg.recipe
packaging was failing with a path error- .pkg/Scripts is inside
/Unpacked folder.
=> Add /Unpacked to path

JetBrains/IDEA-IU.munki.recipe
=> adding in Intellij IDEA Ultimate munki recipe

JetBrains/IDEA-IU.munki.recipe, JetBrains/RubyMine.munki.recipe
Downloads and successfully imports into munki.
=> Added rubymine munki recipe. 

mysides/mysides.download.recipe, mysides/mysides.install.recipe, mysides/mysides.munki.recipe
Cheers...figured it makes more sense for you to host it since you're the dev.
Doubt much maintenance will be needed on these recipes.
=> add mysides recipes

JetBrains/PhpStorm.munki.recipe
added Munki recipe for PhpStorm
=> +added Munki recipe for PhpStorm

JetBrains/PhpStorm.download.recipe
Please verify code signing after download.
=> CodesignatureVerifier already at download

SaltStack/salt-py3.download.recipe, SaltStack/salt-py3.munki.recipe
updating salt.download to pull the latest version, and adding in python3 versions  of download and munki
```
Processing ./SaltStack/salt.munki.recipe...
WARNING: ./SaltStack/salt.munki.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
URLTextSearcher
{'Input': {'re_pattern': u'Latest release: ([\\d\\.]+)',
'result_output_var_name': u'version',
'url': u'https://repo.saltstack.com/#osx'}}
URLTextSearcher: No value supplied for CURL_PATH, setting default value of: /usr/bin/curl
URLTextSearcher: Found matching text (version): 2017.7.4
{'Output': {u'version': '2017.7.4'}}
URLDownloader
{'Input': {'CURL_PATH': '/usr/bin/curl',
'url': u'https://repo.saltstack.com/osx/salt-2017.7.4-py2-x86_64.pkg'}}
URLDownloader: No value supplied for CHECK_FILESIZE_ONLY, …
```
=> salt recipe updates

SaltStack/salt.download.recipe, SaltStack/salt.install.recipe
Add .install recipe, codesig verif and input variable within salt.download recipe to switch between py2 and 3 pkg variants
=> Revise download and add .install

Adobe/CaptivateELearningAssets.download.recipe, ItsApparent/BarcodeProducer.download.recipe, Linotype/FontExplorerXServer.download.recipe, ProjectWizards/Merlin.download.recipe
I tested the modified recipes with `autopkg run --check` but you may want to do the same just to be sure.
=> Update to HTTPS

JetBrains/JetbrainsURLProvider.py
=> fix urllib import

XRite/i1Profiler.munki.recipe
Corrected the path for the version processor
=> Path for versioner changed

Adobe/AcrobatProCustomizationWizardRunner.py
Replaced plistlib.writePlistToString() and FoundationPlist.writePlist() as these call are deprecated in Python 3
=> Python 3 compatibility changes for AcrobatProCustomizationWizardRunner.py (as used in AdobeAcrobatProBaseCustomized.munki.recipe)

XRite/i1Profiler.download.recipe
In relation to issue #46 but will affect the pkg recipe as per issue #47
=> Updated the Sparkle Feed URL and added CodeSignatureVerifier

Adobe/AdobeAcrobatProBase.download.recipe, Adobe/CaptivateTTSVoices.download.recipe, Seafile/SeafileClient.download.recipe, Strata/HDRLightStudio.download.recipe, Strata/Strata3DDesignCX.download.recipe, Synalysis/SynalyzeItPro.download.recipe
Detected and changed HTTPS URLs automatically using my [HTTPS Spotter](https://www.elliotjordan.com/posts/autopkg-https/) script, and then tested all changed recipes manually to ensure download success.
=> Update all available URLs from HTTP to HTTPS

SaltStack/salt-py3.munki.recipe
It appears in the most recent Saltstack release (3003.3) that they added a 'v' in the built PKG version. This keeps the clean version that was previously used on the admin side of things:
```
autopkg run -vv ~/Documents/git/mosen-recipes/SaltStack/salt-py3.munki.recipe 11:48:24
Processing /Users/autopkgadm/Documents/git/mosen-recipes/SaltStack/salt-py3.munki.recipe...
WARNING: /Users/autopkgadm/Documents/git/mosen-recipes/SaltStack/salt-py3.munki.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
URLTextSearcher
{'Input': {'re_pattern': 'Latest release: ([\\d\\.]+)',
'result_output_var_name': 'version',
'url': 'https://repo.saltstack.com/#osx'}}
URLTextSearcher: Found matching text (version): 3003.3
{'Output': {'version': '3003.3'}}
URLDownloader …
```
=> Force collected Saltstack version from website for import

JetBrains/JetbrainsURLProvider.py
New product from JetBrains => https://www.jetbrains.com/remote-development/gateway/
=> Add new PRODUCT_CODE for JetBrains Gateway

JetBrains/JetbrainsURLProvider.py
=> Missed comma in prev JetBrains Gateway PR

JetBrains/clion.munki.recipe, JetBrains/datagrip.munki.recipe, JetBrains/jetbrains.download.recipe
This will add a jetbrains.download.recipe to use in other jetbrains munki recipes easily. Then I used the new downloader for the clion app and the datagrip app. 
datagrip output: 
```
Processing ./datagrip.munki.recipe...
{'AUTOPKG_VERSION': '2.7.2',
'MUNKI_CATEGORY': 'Developer',
'MUNKI_REPO': '/Users/kbrewer/Development/munki/repo',
'MUNKI_REPO_SUBDIR': 'apps/datagrip',
'NAME': 'DataGrip',
'PARENT_RECIPES': ['/Users/kbrewer/Development/forks/mosen-recipes/JetBrains/jetbrains.download.recipe'],
'PLATFORM': 'mac',
'PRODUCT_CODE': 'DG',
'PRODUCT_IDENTIFIER': 'com.jetbrains.datagrip',
'RECIPE_CACHE_DIR': '/Users/kbrewer/Library/AutoPkg/Cache/com.github.mosen.munki.DataGrip',
'RECIPE_DIR': '/Users/kbrewer/Development/forks/mosen-recipes/JetBrains',
'RECIPE_OVERRIDE_DIRS': …
```
=> Add jetbrains download recipe and Clion & datagrip munki recipes

Appsforlife/Origami.download.recipe
This PR updates the Origami recipes for version 3, and adds an ARCH input variable that allows specifying which version (Intel or Apple Silicon) to download. A MAJOR_VERSION input variable has also been added to ease the transition to future versions of the software.
Verbose recipe run output for default (Intel) architecture:
```
% autopkg run -vvq 'Appsforlife/Origami.download.recipe'
Processing Appsforlife/Origami.download.recipe...
WARNING: Appsforlife/Origami.download.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
URLTextSearcher
{'Input': {'re_pattern': '//(cdn\\.appsforlife\\.com/origami/3/[\\d\\.]+/Origami3_Intel\\.dmg)',
'result_output_var_name': 'urlpath',
'url': 'https://boxshot.com/downloads/'}}
URLTextSearcher: Found matching text …
```
=> Fix Origami recipes and add ARCH and MAJOR_VERSION input variables

Appsforlife/Boxshot.download.recipe
This PR updates the Boxshot recipes for version 5, and adds an ARCH input variable that allows specifying which version (Intel or Apple Silicon) to download. A MAJOR_VERSION input variable has also been added to ease the transition to future versions of the software.
Verbose recipe run output for default (Intel) architecture:
```
% autopkg run -vvq 'Appsforlife/Boxshot.download.recipe'
Processing Appsforlife/Boxshot.download.recipe...
WARNING: Appsforlife/Boxshot.download.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
URLTextSearcher
{'Input': {'re_pattern': '//(cdn\\.appsforlife\\.com/boxshot/5/[\\d\\.]+/Boxshot5_Intel\\.dmg)',
'result_output_var_name': 'urlpath',
'url': 'https://boxshot.com/downloads/'}}
URLTextSearcher: Found matching text …
```
=> Fix Boxshot recipes and add ARCH and MAJOR_VERSION input variables
